### PR TITLE
New deployment today! -- Updating CHANGELOG.

### PR DESCRIPTION
**Pull request by zorn**
No ticket/issue.

@kotarofujita Please give this a once over and merge if happy.

Also with this, the website app is ready for you to do some QA! Make some groups by starting here:

https://manager.guildflow.com

I can delete them later to clean up -- so go wild!

### CODE REVIEW

**Comment by kotarofujita** [comment]
Mozilla spelling. 

Screen Shot 2020-08-12 at 8 12 59 AM

**Comment by kotarofujita** [comment]
Feature request: Maybe refill the start date with today AND/OR provide a calendar picker.

image

**Comment by kotarofujita** [comment]
Might have been me but I got a little confused why there wasn't an "add/invite user" button here which would take me to the Membership Application page.

Screen Shot 2020-08-12 at 8 19 23 AM

**Comment by kotarofujita** [comment]
Maybe not implemented yet but would be nice to auto-attend whomever is the one to create the event.

Screen Shot 2020-08-12 at 8 22 21 AM

**Comment by zorn** [comment]
I went through these notes and my own from our meeting and made tickets for the big ideas.

Looks like the CHANGELOG itself is ok? Will be merging shortly.

**Pull request merged**
